dudu/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView


urlpatterns = [
    path('restricted/private/admin/', admin.site.urls),
    #path('message/', include('message.urls', namespace='message')),
    path('reception/', include('reception.urls', namespace='reception')),
    path('', RedirectView.as_view(permanent=True, url='/reception/'), name='index')
]

message/urls.py
from django.conf.urls import url
from .views import index, add_surat, delete_surat
#url for app
app_name = 'message'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_surat', add_surat, name='add_surat'),
    url(r'^delete_surat/(?P<id_num>\d+)/$', delete_surat, name='delete_surat'),
]

reception/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'reception'
urlpatterns = [
    path('', views.index, name='index'),
    url(r'^add_guest', views.add_guest, name='add_guest'),
]

message/models.py
from django.db import models

# Create your models here.
class Surat(models.Model):
	dari = models.CharField(max_length=30)
	untuk = models.CharField(max_length=30)
	pesan = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	

reception/models.py
from django.db import models

# Create your models here.
class Guest(models.Model):
	nama = models.CharField(max_length=50)
	email = models.EmailField(max_length=50)
	answer = models.CharField(max_length=10)
	
	def __str__(self):
		return self.answer + '   ' + self.nama + ':        ' + self.email

message/forms.py
from django import forms

class Surat_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    dari_attrs = {
        'type': 'text',
        'class': 'surat-form-input',
        'placeholder':'Masukan nama pengirim'
    }
    untuk_attrs = {
        'type': 'text',
        'class': 'surat-form-input',
        'placeholder':'Masukan nama penerima'
    }
    pesan_attrs = {
        'type': 'text',
        'cols': 50,
        'rows': 4,
        'class': 'surat-form-textarea',
        'placeholder':'Masukan pesanmu'
    }

    dari = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=dari_attrs))
    untuk = forms.CharField(label='', required=True, max_length=30, widget=forms.TextInput(attrs=untuk_attrs))
    pesan = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=pesan_attrs))

reception/forms.py
from django import forms

class Guest_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
    }
    nama_attrs = {
        'type': 'text',
        'class': 'guest-form-input',
        'placeholder':'Name'
    }
    email_attrs = {
        'type': 'email',
        'class': 'guest-form-input',
        'placeholder':'Email'
    }

    nama = forms.CharField(label='', required=True, max_length=50, widget=forms.TextInput(attrs=nama_attrs))
    email = forms.EmailField(label='', required=True, max_length=50, widget=forms.TextInput(attrs=email_attrs))
    
    CHOICES = ((1, 'Will definitely be there!',), (2, 'Sorry, I can\'t make it',))
    answer = forms.ChoiceField(label='', required=True,widget=forms.RadioSelect, choices=CHOICES)

message/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Surat_Form
from .models import Surat

# Create your views here.
response = {}
def index(request):
    response['author'] = "Rahmania Astrid Mochtar" #TODO Implement yourname
    surat = Surat.objects.all()
    response['surat'] = surat
    html = 'message/message.html'
    response['surat_form'] = Surat_Form
    return render(request, html, response)

def add_surat(request):
    form = Surat_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['dari'] = request.POST['dari']
        response['untuk'] = request.POST['untuk']
        response['pesan'] = request.POST['pesan']
        surat = Surat(dari=response['dari'],untuk=response['untuk'],pesan=response['pesan'])
        surat.save()
        return HttpResponseRedirect('/message/')
    else:
        return HttpResponseRedirect('/message/')

def delete_surat(request, id_num):
    surat = Surat.objects.get(pk=id_num)
    surat.delete()
    return HttpResponseRedirect('/message/')

reception/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Guest_Form
from .models import Guest

# Create your views here.
response = {}
def index(request):
    html = 'reception/another.html'
    guest = Guest.objects.all()
    response['guest'] = guest
    response['guest_form'] = Guest_Form
    return render(request, html, response)

def add_guest(request):
    form = Guest_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['nama'] = request.POST['nama']
        response['email'] = request.POST['email']
        print(request.POST['answer'])
        if request.POST['answer'] == '1':
            response['answer'] = 'YES'
        else:
            response['answer'] = 'NO'
        guest = Guest(nama=response['nama'],email=response['email'], answer=response['answer'])
        guest.save()
        return HttpResponseRedirect('/reception/')
    else:
        return HttpResponseRedirect('/reception/')

message/templates/message/layout/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="{{author}}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/message.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oswald:400,700" rel="stylesheet">
    <title>
        {% block title %} DUDU By {{author}} {% endblock %}
    </title>
</head>

<body>
    <content>
        {% block content %}
        {% endblock %}
    </content>
    <footer>
        {% block footer %}
        {% include "message/partials/footer.html" %}
        {% endblock %}
    </footer>

    <script type="application/javascript">
      

    </script>
</body>
</html>

message/templates/message/message.html
{% extends "message/layout/base.html" %}

{% block content %}

<h2>Tulislah sesuai keinginan hatimu</h2>

<div class="contain-form">
	<div class="form-web">
		<form id="form" method="POST" action="{% url 'message:add_surat' %}">
			{% csrf_token %}
			{{ surat_form }}
			<input id="submit" type="submit" class="input-btn" value="Submit">
		</form>	
	</div>
</div>


<div class="posts">
	{% if surat %}
		<div class="contain-surat">
			{% for post in surat reversed %}
				<div class="surat-post">
					<div class="surat-dari">
						DARI: {{post.dari}}
					</div>
					<div class="surat-untuk">
						UNTUK: {{post.untuk}}
					</div>
					<div class="surat-pesan">
						{{post.pesan}}
					</div>
					<a href="/message/delete_surat/{{ post.id }}">
						<div class="post-delete">
							HAPUS
						</div>
					</a>
				</div>
			{% endfor %}
		</div>
		
	{% else %}
		<div class="no-posts">
			Wadaw! Kasihan tidak ada yang menulis:(
		</div>
	{% endif %}
</div>


{% endblock %}

message/templates/message/partials/footer.html
<p>Created by the ever wonderful <a href="https://rahmaniaam.github.io">Rahmania Astrid Mochtar</a></p>

reception/templates/reception/another.html
{% load staticfiles %} {% load static %}
<!DOCTYPE html>
<html>

<head>
    <title>Hera & Yovan</title>
    <meta charset='utf-8' />
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:100,400" rel="stylesheet">
    <link href="{% static 'css/large.css' %}" rel="stylesheet">

    <style>
        @font-face {
            font-family: 'scriptinaregular';
            src: url("{% static 'fonts/scriptin-webfont.woff2' %}") format('woff2'),
            url("{% static 'fonts/scriptin-webfont.woff' %}") format('woff');
            font-weight: normal;
            font-style: normal;
        }

        @font-face {
            font-family: 'neou';
            src: url("{% static 'fonts/Neou-Thin.ttf' %}") format('truetype');
        }

        /* @media screen and (max-width: 1366px) {
            .lg-img {
                height: 100vh;
            }

            #third-photo {
                top: 0%;
                transform: unset !important;
            }
        } */

        @media screen and (max-width: 414px) {
            .lg-img {
                height: 100vh;
                width: auto;
            }

            #first-photo {
                left: -18%;
                transform: translateX(-18%);
            }

            #second-photo {
                left: -25%;
                transform: translateX(-25%);
            }

            #third-photo {
                width: 100vw;
                transform: none;
            }

            .title {
                font-size: 1.5rem;
            }

            #demo {
                width: 50%;
                font-size: 0.9rem;
            }

            .mugshot-container {
                display: flex;
                flex-direction: column;
            }

            .crop {
                margin: 2rem 3rem 0rem 3rem;
            }

            .bride-desc,
            .groom-desc,
            .name {
                position: relative;
                top: -10%;
                transform: translateY(-10%);
            }

            .name {
                position: relative;
                top: -100%;
                transform: translateY(-200%);

                margin: 1rem;
                font-size: 1.2rem;
            }

            .story-title {
                font-size: 1.5rem;
            }

            .story-text {
                font-size: 1rem;
                padding: 0.1rem;
            }

            .message-title {
                font-size: 2rem;
            }

            .message-desc {
                font-size: 1.5rem;
                padding-bottom: 4rem;
            }

            .calendar {
                min-height: 50vh;
                font-size: 1.7rem;
            }

            .rsvp-container {
                font-size: 1rem;
                padding: 1rem;
                height: 100vh;
            }

            input[type=text],
            input[type=email] {
                font-size: 1rem;
            }

            .slide {
                overflow: hidden;
            }

            .map-title {
                font-size: 2rem;
            }

            .ann-title {
                font-size: 1.5rem;
            }

            .ann-desc {
                font-size: 1rem;
                padding-bottom: 4rem;
            }

            #map {
                height: 100vw;
                width: 100vw;
                margin: 0 auto;
            }

        }
    </style>
</head>


<body>
    <div class="landing">
        <div class="slideshow">
            <div class="slide fade">
                <img id="first-photo" class="lg-img" src="{% static 'assets/_DSC5694.jpg' %}" width="100%">
            </div>
            <div class="slide fade">
                <img id="second-photo" class="lg-img" src="{% static 'assets/_DSC5809.jpg' %}" width="100%">
            </div>
            <div class="slide fade">
                <img id="third-photo" class="lg-img" src="{% static 'assets/_DSC6039.jpg' %}" width="100%">
            </div>
        </div>

        <p class="title">Hera & Yovan</p>
        <p id="demo" style="font-family: Roboto Slab;"></p>
    </div>

    <div class="mugshot-container">
        <div class="bride">
            <div class="bride-container crop">
                <img class="bride-img" src="{% static 'assets/_DSC5936.jpg' %}" width=100%>
            </div>
            <div class="bride-desc">
                The Bride
            </div>
            <div class="name" style="font-family: 'neou';">
                Rezania Khairani Mochtar
            </div>
        </div>
        <div class="groom">
            <div class="groom-container crop">
                <img class="groom-img" src="{% static 'assets/_DSC5941.jpg' %}" width=100%>
            </div>
            <div class="groom-desc">
                The Groom
            </div>
            <div class="name" style="font-family: 'neou';">
                Yovan Hadiatma Malikul Mulki
            </div>
        </div>
    </div>

    <div class="story">

        <fieldset>
            <legend class="story-title" style="font-family: Roboto Slab;">The Story of Us</legend>
            <div class="story-text" style="font-family: Roboto Slab;">
                <p>We never remember our first meeting. Since it was years ago, and we didn’t even care. So it wasn’t love at
                    first sight. Nor was it any other fairytale stories. But God’s fate has brought us together and it was
                    more than magical!
                </p>
                <p>
                    Our grand families come from the same root, the infamous Kotogadang, West Sumatra. So our families knew one another. We even
                    have mutual relatives. The funny thing is, we only started to recognize each other back in 2013.
                </p>
                <p>After almost 5 years of relationship, partially long distance, we decided to bring it to the next level.
                    And now here we are, just a few days before our wedding day.
                </p>
            </div>
        </fieldset>
    </div>

    <div class="message-container" style="font-family: Roboto Slab;">
        <p class="message-title">Dear Friends &amp; Families,</p>
        <br>
        <p class="message-desc">Our big day is getting closer. Without your presence, our happiness won’t be complete. Please be delighted to join
            the celebration. We’ll see you there!</p>
        <p class="message-name" style="font-family: scriptinaregular;">Hera &amp; Yovan</p>
    </div>

    <div class="calendar" style="font-family: neou;">
        <p>
            Sunday, 22 July 2018
            <br>
            <br> Reception
            <br> 19.00 - 22.00
            <br> Birawa Assembly Hall,
            <br> Hotel Bidakara
        </p>
        <br>
        <span>
            <a target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&amp;tmeid=Yzh0YzVudWVoZWM0dDdmbTVkYjRnaDVpczhfMjAxODA3MjJUMTIwMDAwWiByYWhtYW5pYWFtMjZAbQ&amp;tmsrc=rahmaniaam26%40gmail.com&amp;scp=ALL">
                <b>Add the wedding </b>
            </a>
            to your google calendar!
        </span>
    </div>

    <div class="rsvp-container" style="font-family: Roboto Slab;">
        Kindly confirm your presence
        <div class="rsvp-form">
            <form id="form" method="POST" action="{% url 'reception:add_guest' %}">
                {% csrf_token %} {{ guest_form }}
                <input id="submit" type="submit" class="input-btn" value="Submit">
            </form>
        </div>
    </div>

    <div class="map-container" style="font-family: Roboto Slab;">
        <p class="map-title">Don't get lost, we have technology.</p>
        <div id="map"></div>
        <a href="https://www.google.com/maps/place/Hotel+Bidakara+Jakarta/@-6.2402491,106.8397694,17z/data=!3m1!4b1!4m7!3m6!1s0x2e69f3bf7ae976e1:0x4acba2b6160b7c19!5m1!1s2018-07-10!8m2!3d-6.2402491!4d106.8419581">
            <b>(Open in google maps)</b>
        </a>
        <br>
        <br>
        <br>
        <p class="ann-title">Important announcement!</p>
        <br>
        <p class="ann-desc">
            Please be informed that there will be an expansion of "Ganjil-Genap" area. Kindly study
            <b>
                <a href="{% static 'file/ganjil-genap.pdf' %}">this</a>
            </b> to find an alternative to get to the venue.
        </p>

    </div>

</body>

<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/maps.js' %}"></script>

<script>
    var slideIndex = 0;
    showSlides();

    function showSlides() {
        var i;
        var slides = document.getElementsByClassName("slide");
        for (i = 0; i < slides.length; i++) {
            slides[i].style.display = "none";
        }
        slideIndex++;
        if (slideIndex > slides.length) { slideIndex = 1 }
        slides[slideIndex - 1].style.display = "block";
        setTimeout(showSlides, 2500);
    }
</script>

<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAyK-gR_wVlDvmBa8_FpK5ylSJccxh3IKc&callback=initMap"></script>

</html>